language: d

# Trusty is Travis' default but reached EOL 2019-04-30
dist: xenial

os:
  - linux
  - osx

d:
  - dmd
  - ldc
  - dmd-2.085.1
  - ldc-1.14.0

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gdc-9
      env: DC=gdc-9
