name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Run
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest, dmd-2.094.1, ldc-1.24.0 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        # For codecov
        fetch-depth: 2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      shell: bash
      run: |
        dub test --compiler=$DC -b unittest-cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
