name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Run
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest, dmd-2.094.1, ldc-1.24.0 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Test'
      shell: bash
      run: |
        dub build --compiler=$DC
        dub test --compiler=$DC -b unittest-cov

    - name: 'Test with -preview=in'
      shell: bash
      run: |
        # Can't use `dub` because of:
        # https://github.com/dlang/dub/pull/2005#issuecomment-786531340
        $DC -preview=in -unittest -main -run source/geod24/bitblob.d

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
